config/routes.rb
Rails.application.routes.draw do
  resources :diaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'users', to: 'users#index'
  get 'users/new'
  get 'users/:id', to:'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :diaries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[ show edit update destroy ]

  # GET /diaries or /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1 or /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries or /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: "Diary was successfully created." }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: "Diary was successfully updated." }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: "Diary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% diary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">日記一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>登録日時</th>
      <th>更新日時</th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.id %></td>
        <td><%= link_to diary.title, diary %></td>
        <td><%= diary.created_at %></td>
        <td><%= diary.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新規作成', new_diary_path %>

app/views/diaries/new.html.erb
<h1>New Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="content">
  <h1><%= @diary.title %></h1>
  <p><%= @diary.body %></p>
</div>
<nav class="level">
  <div class="level-left">
    <p><strong>作成者</strong> <%= link_to @diary.user.name, "/users/#{@diary.user.id}" %></p>
  </div>
  <div class="level-right">
    <div class="level-item">
      <p><strong>登録日時</strong> <%= @diary.created_at %></p>
    </div>
    <div class="level-item">
      <p><strong>更新日時</strong> <%= @diary.updated_at %></p>
    </div>
  </div>
</nav>

<%= link_to '編集する', edit_diary_path(@diary) %> |
<%= link_to '削除する', @diary, method: :delete, data: { confirm: '本当に削除しますか？' } %> |
<%= link_to '一覧に戻る', diaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Rails Sample App
        </a>
      </div>
    </nav>
    <section class="main section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
    <footer class="footer">
      <div class="content has-text-centered">
        <p><a href="https://github.com/kecbigmt/rails-sample-app" target="_blank" rel="noopener noreferrer">GitHub</a></p>
      </div>
    </footer>
  </body>
</html>

app/views/users/index.html.erb
<h1 class="title">ユーザー一覧</h1>
<table class="table">
  <thead>
    <th>ID</th>
    <th>名前</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.name, "/users/#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div>Hello, Japan!</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1 class="title">プロフィール</h1>
  <p class="subtitle"><strong><%= @user.name %></strong><br><%= @user.bio %></p>
  <table class="table">
    <thead>
      <th>ID</th>
      <th>タイトル</th>
      <th>登録日時</th>
      <th>更新日時</th>
    </thead>
    <tbody>
      <% @user.diaries.each do |diary| %>
        <tr>
          <td><%= diary.id %></td>
          <td><%= link_to diary.title, diary %></td>
          <td><%= diary.created_at %></td>
          <td><%= diary.updated_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>